sonar.projectKey=smartdockershrinker
sonar.projectName=Smart Docker Shrinker
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/.git/**,**/node_modules/**,helm/**,infra/**
sonar.python.version=3.11
